#spring.profiles.active: @spring.profiles.active@
spring:
  profiles.active: development-h2

server:
  port: 8081

---
spring:
  profiles: development-h2
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./localDB/restaurantDB;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;MVCC=FALSE
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
flyway:
  locations: classpath:/db/migration/H2
  user: sa
  password: