server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address:127.0.0.1}
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
